### ISSUE TITLE
Tag a release?

### ISSUE THREAD

**Issue by dpryan79** [marianogabitto/ChromA#2]
Can you tag a release for ChromA so others can refer to a specific version when using it?

**Comment by marianogabitto** [comment]
Dear Ryan,
      the master branch has been tagged. However, at ay point, the master branch has the most updated and validated version of ChromA.

      Please, give it a try and do not hesitate in contacting me if you have troubles at any point (mgabitto@flatironinstitute.org). We have validated the installation in 3 different computer clusters but there could be problems. 

Thanks,

M

**Comment by dpryan79** [comment]
Thanks, I'll add it to bioconda so it should then work more or less anywhere.

**Comment by marianogabitto** [comment]
Ryan,
    how do you add it to bioconda? Would the Bioconda installer keep track of the latest version on the master branch?

M

**Comment by dpryan79** [comment]
We only track tagged releases, which is what your end users should be relying on anyway.

BTW, nice talk at ISMB today.

**Comment by marianogabitto** [comment]
Hey... lost track of this... 

Thanks for the comment!

I realized that I never uploaded the tags to Git and I kept them locally... Hopefully, it is still time to tag the release on BioConda :)

**Comment by dpryan79** [comment]
Thanks!
